image: ${CI_REGISTRY}/utilities/build-images/ubuntu-18-04-build:master
stages:
  - deploy

# jobs:

deploy:toGithub:
  stage: deploy
  when: manual
  only:
    - branches
  tags:
    - docker
  environment:
    name: github
    url: https://github.com/liaFeier23/api.github.io
  script:
    - git lfs fetch --all
    - git remote add public https://oauth2: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@github.com/liaFeier23/api.github.io.git
    - git pull public main
    - git push public HEAD:refs/heads/${CI_COMMIT_REF_NAME}
  after_script:
    - git remote remove public
